# Simple workflow for deploying static content to GitHub Pages
name: E2E testing

on:
  # Runs on Pull request
  pull_request:
    branches: ["master", "workflow"]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "E2E tests"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just testing
  cypressE2ETests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
      - name: Install Dependencies  
        run: npm i
      - name: Build SASS
        run: npm run build
      - name: Cypress run  
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/e2e
        env:
            EMAIL: ${{secrets.EMAIL}}
            PASSWORD: ${{secrets.PASSWORD}}
